# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Create CSS directory
        run: mkdir -p $GITHUB_WORKSPACE/css/themes
      
      - name: Compile structure.scss
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/structure.scss
          destination: css/structure.css
      
      - name: Compile louglu.scss
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/louglu.scss
          destination: css/louglu.css
      
      - name: Compile BBN Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/bbn.scss
          destination: css/themes/bbn.css
      
      - name: Compile Blue Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/blue.scss
          destination: css/themes/blue.css
          
      - name: Compile Default Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/default.scss
          destination: css/themes/default.css

      - name: Compile Green Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/green.scss
          destination: css/themes/green.css
      
      - name: Compile L1C4 Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/l1c4.scss
          destination: css/themes/l1c4.css
      
      - name: Compile Orange Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/orange.scss
          destination: css/themes/orange.css
      
      - name: Compile Pink Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/pink.scss
          destination: css/themes/pink.css
      
      - name: Compile Pride Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/pride.scss
          destination: css/themes/pride.css
      
      - name: Compile Red Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/red.scss
          destination: css/themes/red.css
      
      - name: Compile USA Theme
        uses: gha-utilities/sass-build@v0.2.7
        with:
          source: scss/themes/usa.scss
          destination: css/themes/usa.css
      
      - name: Upload Site Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: $GITHUB_WORKSPACE
